# Site settings
title: Missouri S&T IAM
email: mleu@mst.edu
description: "Missouri S&T - Innovative Additive Manufacturing Laboratory"
baseurl: "/~mstiam"
url: "http://web.mst.edu/~mstiam"
# GITHUB PAGES:
#baseurl: ""
#url: "mstiam.github.io"
encoding: utf-8
github_username: mstiam

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-feed
  - jekyll/scholar

exclude:
  - Gemfile
  - Gemfile.lock

scholar:
  source: ./_data
  bibliography: publications.bib
  style: _csl/chicago_titlefirst.csl
  bibliography_template: bib
  locale: en
  sort_by: year
  order: descending
  #details_dir: bibliography
  #details_layout: bibtex.html
  #details_link: Details
  #query: "@*"
