# Site settings
title: Missouri S&T IAM
email: km89f@mst.edu
description: ""
baseurl: ""
url: "iam-mst.github.io"
encoding: ISO-8859-1
github_username:  koosham

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-feed
  - jekyll/scholar

exclude:
  - Gemfile
  - Gemfile.lock

scholar:
  source: ./_data
  bibliography: publications.bib
  style: _csl/mla.csl
  locale: en
  sort_by: none
  order: ascending
  #details_dir:    bibliography
  #details_layout: bibtex.html
  #details_link:   Details
  #query: "@*"
