# Site settings
title: Missouri S&T IAM
email: km89f@mst.edu
description: ""
baseurl: ""
url: "iam-mst.github.io"
encoding: ISO-8859-1
github_username:  koosham

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
